FROM golang:1.25-alpine AS builder

WORKDIR /app
COPY . .

RUN go mod tidy
RUN GOOS=linux go build -a -installsuffix cgo -o main .


FROM alpine:latest AS final

WORKDIR /root/
COPY --from=builder /app/main .

CMD ["./main"]